/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdSettingsRouteImport } from './routes/_authenticated/ad-settings'
import { Route as AuthenticatedAiCreateRouteImport } from './routes/_authenticated/ai-create'
import { Route as AuthenticatedAiDesignRouteImport } from './routes/_authenticated/ai-design'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedImageToPdfRouteImport } from './routes/_authenticated/image-to-pdf'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedPdfEditorRouteImport } from './routes/_authenticated/pdf-editor'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedCreateTypeRouteImport } from './routes/_authenticated/create.$type'
import { Route as AuthenticatedDesignTypeRouteImport } from './routes/_authenticated/design.$type'
import { Route as AuthenticatedDocIdRouteImport } from './routes/_authenticated/doc.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdSettingsRoute = AuthenticatedAdSettingsRouteImport.update({
  id: '/ad-settings',
  path: '/ad-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCreateRoute = AuthenticatedAiCreateRouteImport.update({
  id: '/ai-create',
  path: '/ai-create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiDesignRoute = AuthenticatedAiDesignRouteImport.update({
  id: '/ai-design',
  path: '/ai-design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageToPdfRoute = AuthenticatedImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdfEditorRoute = AuthenticatedPdfEditorRouteImport.update({
  id: '/pdf-editor',
  path: '/pdf-editor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateTypeRoute = AuthenticatedCreateTypeRouteImport.update({
  id: '/create/$type',
  path: '/create/$type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignTypeRoute = AuthenticatedDesignTypeRouteImport.update({
  id: '/design/$type',
  path: '/design/$type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocIdRoute = AuthenticatedDocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ad-settings': typeof AuthenticatedAdSettingsRoute
  '/ai-create': typeof AuthenticatedAiCreateRoute
  '/ai-design': typeof AuthenticatedAiDesignRoute
  '/home': typeof AuthenticatedHomeRoute
  '/image-to-pdf': typeof AuthenticatedImageToPdfRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/pdf-editor': typeof AuthenticatedPdfEditorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/create/$type': typeof AuthenticatedCreateTypeRoute
  '/design/$type': typeof AuthenticatedDesignTypeRoute
  '/doc/$id': typeof AuthenticatedDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ad-settings': typeof AuthenticatedAdSettingsRoute
  '/ai-create': typeof AuthenticatedAiCreateRoute
  '/ai-design': typeof AuthenticatedAiDesignRoute
  '/home': typeof AuthenticatedHomeRoute
  '/image-to-pdf': typeof AuthenticatedImageToPdfRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/pdf-editor': typeof AuthenticatedPdfEditorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/create/$type': typeof AuthenticatedCreateTypeRoute
  '/design/$type': typeof AuthenticatedDesignTypeRoute
  '/doc/$id': typeof AuthenticatedDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ad-settings': typeof AuthenticatedAdSettingsRoute
  '/_authenticated/ai-create': typeof AuthenticatedAiCreateRoute
  '/_authenticated/ai-design': typeof AuthenticatedAiDesignRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/image-to-pdf': typeof AuthenticatedImageToPdfRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/pdf-editor': typeof AuthenticatedPdfEditorRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/create/$type': typeof AuthenticatedCreateTypeRoute
  '/_authenticated/design/$type': typeof AuthenticatedDesignTypeRoute
  '/_authenticated/doc/$id': typeof AuthenticatedDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ad-settings'
    | '/ai-create'
    | '/ai-design'
    | '/home'
    | '/image-to-pdf'
    | '/library'
    | '/pdf-editor'
    | '/profile'
    | '/scan'
    | '/create/$type'
    | '/design/$type'
    | '/doc/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ad-settings'
    | '/ai-create'
    | '/ai-design'
    | '/home'
    | '/image-to-pdf'
    | '/library'
    | '/pdf-editor'
    | '/profile'
    | '/scan'
    | '/create/$type'
    | '/design/$type'
    | '/doc/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ad-settings'
    | '/_authenticated/ai-create'
    | '/_authenticated/ai-design'
    | '/_authenticated/home'
    | '/_authenticated/image-to-pdf'
    | '/_authenticated/library'
    | '/_authenticated/pdf-editor'
    | '/_authenticated/profile'
    | '/_authenticated/scan'
    | '/_authenticated/create/$type'
    | '/_authenticated/design/$type'
    | '/_authenticated/doc/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ad-settings': {
      id: '/_authenticated/ad-settings'
      path: '/ad-settings'
      fullPath: '/ad-settings'
      preLoaderRoute: typeof AuthenticatedAdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-create': {
      id: '/_authenticated/ai-create'
      path: '/ai-create'
      fullPath: '/ai-create'
      preLoaderRoute: typeof AuthenticatedAiCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-design': {
      id: '/_authenticated/ai-design'
      path: '/ai-design'
      fullPath: '/ai-design'
      preLoaderRoute: typeof AuthenticatedAiDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image-to-pdf': {
      id: '/_authenticated/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof AuthenticatedImageToPdfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdf-editor': {
      id: '/_authenticated/pdf-editor'
      path: '/pdf-editor'
      fullPath: '/pdf-editor'
      preLoaderRoute: typeof AuthenticatedPdfEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create/$type': {
      id: '/_authenticated/create/$type'
      path: '/create/$type'
      fullPath: '/create/$type'
      preLoaderRoute: typeof AuthenticatedCreateTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/$type': {
      id: '/_authenticated/design/$type'
      path: '/design/$type'
      fullPath: '/design/$type'
      preLoaderRoute: typeof AuthenticatedDesignTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doc/$id': {
      id: '/_authenticated/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof AuthenticatedDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdSettingsRoute: typeof AuthenticatedAdSettingsRoute
  AuthenticatedAiCreateRoute: typeof AuthenticatedAiCreateRoute
  AuthenticatedAiDesignRoute: typeof AuthenticatedAiDesignRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedImageToPdfRoute: typeof AuthenticatedImageToPdfRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPdfEditorRoute: typeof AuthenticatedPdfEditorRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedCreateTypeRoute: typeof AuthenticatedCreateTypeRoute
  AuthenticatedDesignTypeRoute: typeof AuthenticatedDesignTypeRoute
  AuthenticatedDocIdRoute: typeof AuthenticatedDocIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdSettingsRoute: AuthenticatedAdSettingsRoute,
  AuthenticatedAiCreateRoute: AuthenticatedAiCreateRoute,
  AuthenticatedAiDesignRoute: AuthenticatedAiDesignRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedImageToPdfRoute: AuthenticatedImageToPdfRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPdfEditorRoute: AuthenticatedPdfEditorRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedCreateTypeRoute: AuthenticatedCreateTypeRoute,
  AuthenticatedDesignTypeRoute: AuthenticatedDesignTypeRoute,
  AuthenticatedDocIdRoute: AuthenticatedDocIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
